# Generated by Django 4.1.7 on 2023-05-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="last_update",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
