# Generated by Django 4.1.7 on 2023-05-27 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_alter_topic_last_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="last_update",
            new_name="last_updated",
        ),
    ]
