# Generated by Django 4.1.7 on 2023-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0003_rename_last_update_topic_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
